### ISSUE TITLE
Add option to discard trace

### ISSUE THREAD

**Issue by hannesastrom** [cacheray/cacheray#14]
When testing the performance of the system, it would be useful to disable the writing to file. This way, you can test the overhead of the logging without measuring how slow your hard-drive is. :)

Something like: CACHERAY_OPTIONS=write=false (default is true).

**Comment by kimgr** [comment]
Could you try setting the tracefile to `/dev/null` and see how that affects the profile?

**Comment by hannesastrom** [comment]
> Could you try setting the tracefile to /dev/null and see how that affects the profile?

It does go faster, not a lot but it is significant. Still, if I am interested in just the pure overhead of the system, without the writing to file, it would be nice to be able to test that.

**Comment by kimgr** [comment]
Yeah, I was curious if it short-circuited enough to count as no overhead.

So if you remove all `fwrite` calls, it's faster still?

**Comment by kimgr** [comment]
And by "overhead of the system", you mean the compiler instrumentation, then, right?

**Comment by kimgr** [comment]
Anyway, my original take was: file i/o is buffered, so the only overhead we'll see is shuffling trace records in memory until the buffer is flushed, at which point it will go to /dev/null and be dropped. I'm not sure how far the data has to travel before the write call realizes that it should be discarded.

**Comment by hannesastrom** [comment]
> And by "overhead of the system", you mean the compiler instrumentation, then, right?

What I refer to as overhead of the system is the calls to the cacheray instrumentation; the logging functions. The writing to file is technically a part of this but I am interested in how much extra time is spent in the runtime :)

> So if you remove all fwrite calls, it's faster still?

Yes, it is even faster!

**Comment by kimgr** [comment]
I wonder if it's fair to measure logging without actual persistence, but OK :-).

I think it would make sense to use the "start-disabled" mode we've discussed before for this kind of overhead measurement. So `enabled` stays off, and we shortcircuit before even building the event records.

A couple of other ideas:

- Change file stream buffer size on startup (`setvbuf`) -- bigger buffer should mean less overhead
- Get rid of the temporary structs and fwrite the data directly to the stream

I'm thinking ideally it would be nice not to have a weird mode that's not useful for anything but profiling, but if there really is no other way, then let's try to decide on a good name for it.

**Comment by hannesastrom** [comment]
> I think it would make sense to use the "start-disabled" mode we've discussed before for this kind of overhead measurement. So enabled stays off, and we shortcircuit before even building the event records.

This is probably the right answer. We should start with adding the **enabled** option :)

> I'm thinking ideally it would be nice not to have a weird mode that's not useful for anything but profiling, but if there really is no other way, then let's try to decide on a good name for it.

With bigger buffer, setting the file to /dev/null would probably come close enough to accurately measure the runtime overhead. Will try it on a larger file.

**Comment by hannesastrom** [comment]
> We should start with adding the enabled option :)

#15

**Comment by kimgr** [comment]
Done, right? Can be closed?

**Comment by hannesastrom** [comment]
Yes box!
