### ISSUE TITLE
Make built-in runtime self-initializing

### ISSUE THREAD

**Issue by kimgr** [cacheray/cacheray#9]
When linking with `libcacheray.a`, I don't think there's any reason why it shouldn't just start recording memory-access events and writing them to file. I think this is what's missing:

* Some way of controlling the output filename and other options (I think we should aim for something like https://github.com/google/sanitizers/wiki/SanitizerCommonFlags)
* Self-initialization so the runtime starts recording as soon as possible

Unless there are any counter-opinions, I can take a stab at this at some point.

**Comment by hannesastrom** [comment]
I think it's a great idea. There already is a sort of name generation scheme in cacheray-utils which pulls a name from an environment variable, but if you have a better scheme I welcome it.

Self-initialization really is crucial so go right ahead.

**Comment by kimgr** [comment]
Fun Christmas project :)

**Comment by kimgr** [comment]
I've hacked at this for a couple of days, and I have a _massive_ diff against `main`.

I'm not sure how to break it up into reasonable chunks and what functionality to keep/drop. I have a bunch of cleanups and improvements I could post separately, but then there's:

- Remove support for cooperative targets (the whole `cacheray_start`/`cacheray_stop` and callback machinery)
- Remove ability to enable/disable cacheray, and instead add per-thread reentrancy handling to suppress instrumentation callbacks when cacheray needs to call out
- Sanitizer-style options parsing (`CACHERAY_OPTIONS=verbosity=1:tracepath=/tmp/xyz.trace`)

In order to get the options parsing in place, I think I have to remove support for cooperative targets. I originally suggested the whole `cacheray_instrum.inc` base runtime to get rid of the callback and instead make it easier to build entire runtimes from scratch. So I don't think the cooperative model has any future, really, I think the runtime should just live in `cacheray.c` and write to file.

If someone needs other runtime behavior, fundamentally different from `cacheray.c`, they can implement their own runtime; it's really trivial based on `cacheray_instrum.inc`.

If we can agree to remove the API from `cacheray.h`: `cacheray_start`, `cacheray_stop`, `cacheray_rtta_add` and `cacheray_rtta_remove`, that will enable the work toward a fully automatic runtime. Thoughts?

**Comment by kimgr** [comment]
Problem is, it's hard to remove the cacheray runtime API without simultaneously implementing a freestanding runtime in cacheray.c. I'll take a stab at making that step as small as possible and post a diff for inspiration.

**Comment by kimgr** [comment]
I like these stats:
```
git diff --stat main 
 cacheray/CMakeLists.txt                    |   4 +--
 cacheray/include/cacheray/cacheray-utils.h |  30 -------------------
 cacheray/include/cacheray/cacheray.h       |  13 ---------
 cacheray/src/cacheray-utils.c              |  98 -------------------------------------------------------------
 cacheray/src/cacheray.c                    | 149 ++++++++++++++++++++++-----------------------------------------------------------------------
 cacheray/test/cooperative/cooperative.c    |  38 ------------------------
 cacheray/test/cooperative/include/sorter.h |   2 ++
 cacheray/test/grand/CMakeLists.txt         |   5 +---
 cacheray/test/grand/grand.c                |  17 -----------
 cacheray/test/structs/CMakeLists.txt       |   3 --
 cacheray/test/structs/main.c               |  22 --------------
 cacheray/tracecheck/CMakeLists.txt         |   3 --
 cacheray/tracecheck/cacheray-trace-check.c |  56 ++++++++++++++++++++++++++++++++++-
 testbench/reorder/Makefile                 |   2 +-
 testbench/reorder/reorder.c                |  13 ---------
 testbench/simple/Makefile                  |   2 +-
 testbench/simple/simple-mt.c               |   7 -----
 testbench/simple/simple-no-instrum.c       |  10 -------
 testbench/simple/simple.c                  |  17 -----------
 19 files changed, 97 insertions(+), 394 deletions(-)
```

I'll post an MR with small increments shortly.

**Comment by kimgr** [comment]
https://github.com/cacheray/cacheray/pull/12

**Comment by hannesastrom** [comment]
2 things:

1. I sort of like this idea where you can start and stop the recording, especially for correctness testing and for checking performance of a certain function/section only.
2. I'm not entirely sure how the system works anymore, can you please explain how the **cacheray_init** function gets called?

**Comment by kimgr** [comment]
> 1. I sort of like this idea where you can start and stop the recording, especially for correctness testing and for
> checking performance of a certain function/section only.

Yeah, it is kind of handy. I think I'd like to re-implement that as:

* A cacheray option passed in environment e.g. `CACHERAY_OPTION=autoinit=0`
* An API to initialize/shutdown and temporarily enable/disable

As I mentioned in the commit message to the last commit, I think we should use reserved names for any cacheray API (e.g. `__cacheray_init`), to follow ASAN and TSAN's lead. It makes sense -- any API between the target application and the cacheray runtime is kind-of an API between the user and the compiler's runtime.

> 2. I'm not entirely sure how the system works anymore, can you please explain how the cacheray_init function gets called?

Sure. The TSAN instrumentation has a `__tsan_init`, which is called for every object file on startup. In the `cacheray_instrum.inc` implementation, we call `cacheray_init` from there. So that's why there needs to be an `is_initialized` guard, because we only want to init once per process.

**Comment by hannesastrom** [comment]
I like this idea of reimplementing it in a different way. Is it proper to merge the current commit onto main as we work on the reimplementation?

> Sure. The TSAN instrumentation has a __tsan_init, which is called for every object file on startup. In the cacheray_instrum.inc implementation, we call cacheray_init from there. So that's why there needs to be an is_initialized guard, because we only want to init once per process.

Thanks! Got it :)

**Comment by kimgr** [comment]
I think it makes sense to merge this as intermediate step. It will be much easier to add options parsing support and other stuff once everything is in cacheray.c.

**Comment by kimgr** [comment]
Let me know if you're fine with merging this as is, and I can take care of that and baseline some other work on it.

**Comment by hannesastrom** [comment]
I'm fine with it. Will use a previous commit for working with precise segments til it gets reimplemented.

**Comment by kimgr** [comment]
Oh, I didn't think you were actively using the explicit control for anything. But if you are, maybe that puts us in a different position. Reimplementing it was pretty low on my prio list, there are lots of other changes I'd like to get in place first.

But maybe if I jump on options next, at least we have infrastructure for exposing the choice to users, which seems pretty important.

Anyway, sounds like you have an escape hatch for now, I'll merge and we can work from there.

**Comment by kimgr** [comment]
Merged as of https://github.com/cacheray/cacheray/pull/12.
